# Generated by Django 3.1.5 on 2021-03-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=0, unique=True),
            preserve_default=False,
        ),
    ]
